server:
  port: 8086

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: 'jdbc:h2:mem:book_store'
    username: admin
    password:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  messages:
    basename: 'lang.messages'
#logging:
#  level:
#    root: debug

