insert into authors (first_name, last_name) values ('Kathi', 'Tydeman');
insert into authors (first_name, last_name) values ('Sanford', 'Youens');
insert into authors (first_name, last_name) values ('Hartwell', 'Escalero');
insert into authors (first_name, last_name) values ('Kaitlyn', 'Jeffcock');
insert into authors (first_name, last_name) values ('Hamel', 'Godfrey');
insert into authors (first_name, last_name) values ('Orrin', 'Dietsche');
insert into authors (first_name, last_name) values ('Sib', 'MacAulay');
insert into authors (first_name, last_name) values ('Ray', 'Roloff');
insert into authors (first_name, last_name) values ('Orton', 'Eger');
insert into authors (first_name, last_name) values ('Lishe', 'Winfred');
insert into authors (first_name, last_name) values ('Reggi', 'Delia');
insert into authors (first_name, last_name) values ('Jay', 'Barrar');
insert into authors (first_name, last_name) values ('Timi', 'Zimmerman');
insert into authors (first_name, last_name) values ('Celesta', 'Albro');
insert into authors (first_name, last_name) values ('Brok', 'Bernasek');
insert into authors (first_name, last_name) values ('Jeanine', 'Ranns');
insert into authors (first_name, last_name) values ('Sigmund', 'Leyzell');
insert into authors (first_name, last_name) values ('Lin', 'Askell');
insert into authors (first_name, last_name) values ('Belvia', 'Bernhart');
insert into authors (first_name, last_name) values ('Barry', 'Rosie');
insert into authors (first_name, last_name) values ('Torin', 'Rousell');
insert into authors (first_name, last_name) values ('Laurens', 'Winterbottom');
insert into authors (first_name, last_name) values ('Sidney', 'Meynell');
insert into authors (first_name, last_name) values ('Jeff', 'Spurrior');
insert into authors (first_name, last_name) values ('Guthrie', 'Heggison');
insert into authors (first_name, last_name) values ('Zarah', 'Matskevich');
insert into authors (first_name, last_name) values ('Donetta', 'Horribine');
insert into authors (first_name, last_name) values ('Nikita', 'Curgenven');
insert into authors (first_name, last_name) values ('Jonis', 'Lansbury');
insert into authors (first_name, last_name) values ('Robin', 'Craighead');
insert into authors (first_name, last_name) values ('Vasili', 'Adamou');
insert into authors (first_name, last_name) values ('Pen', 'McQuorkell');
insert into authors (first_name, last_name) values ('Dyan', 'Ferrers');
insert into authors (first_name, last_name) values ('Raf', 'Nary');
insert into authors (first_name, last_name) values ('Cathlene', 'McGlynn');
insert into authors (first_name, last_name) values ('Emily', 'Crafter');
insert into authors (first_name, last_name) values ('Kattie', 'Graffin');
insert into authors (first_name, last_name) values ('Mona', 'Cartner');
insert into authors (first_name, last_name) values ('Kermit', 'Sears');
insert into authors (first_name, last_name) values ('Marcie', 'Morecomb');
insert into authors (first_name, last_name) values ('Sargent', 'Janeczek');
insert into authors (first_name, last_name) values ('Rhodia', 'Demer');
insert into authors (first_name, last_name) values ('Xavier', 'Cron');
insert into authors (first_name, last_name) values ('Chad', 'Songer');
insert into authors (first_name, last_name) values ('Alexia', 'Bench');
insert into authors (first_name, last_name) values ('Coralie', 'Clell');
insert into authors (first_name, last_name) values ('Ferdinand', 'Chivers');
insert into authors (first_name, last_name) values ('Shurwood', 'Tingey');
insert into authors (first_name, last_name) values ('Lesley', 'Virgoe');
insert into authors (first_name, last_name) values ('Bellina', 'Odger');
insert into authors (first_name, last_name) values ('Stearne', 'Salzburger');
insert into authors (first_name, last_name) values ('Stanford', 'Atkyns');
insert into authors (first_name, last_name) values ('Thaine', 'Sowman');
insert into authors (first_name, last_name) values ('Xenia', 'Dicky');
insert into authors (first_name, last_name) values ('Roldan', 'Beeck');
insert into authors (first_name, last_name) values ('Vern', 'Scarlan');
insert into authors (first_name, last_name) values ('Cloris', 'Vondrach');
insert into authors (first_name, last_name) values ('Emlynn', 'Earey');
insert into authors (first_name, last_name) values ('Cordie', 'Safe');
insert into authors (first_name, last_name) values ('Avram', 'Durkin');
insert into authors (first_name, last_name) values ('Tarra', 'Batteson');
insert into authors (first_name, last_name) values ('Frants', 'Gillebride');
insert into authors (first_name, last_name) values ('Nevile', 'Joicey');
insert into authors (first_name, last_name) values ('Winfield', 'Ilyunin');
insert into authors (first_name, last_name) values ('Sophi', 'Leek');
insert into authors (first_name, last_name) values ('Ilario', 'Shoveller');
insert into authors (first_name, last_name) values ('Witty', 'Limbourne');
insert into authors (first_name, last_name) values ('Ram', 'MacAscaidh');
insert into authors (first_name, last_name) values ('Trudy', 'Abramovitz');
insert into authors (first_name, last_name) values ('Chicky', 'Badsey');
insert into authors (first_name, last_name) values ('Tailor', 'Caistor');
insert into authors (first_name, last_name) values ('Briny', 'Moye');
insert into authors (first_name, last_name) values ('Edmon', 'Merrett');
insert into authors (first_name, last_name) values ('Robers', 'Dodshon');
insert into authors (first_name, last_name) values ('Marris', 'Hand');
insert into authors (first_name, last_name) values ('Briano', 'Fragino');
insert into authors (first_name, last_name) values ('Constantine', 'Peterson');
insert into authors (first_name, last_name) values ('Adara', 'Spowage');
insert into authors (first_name, last_name) values ('Ike', 'Barnish');
insert into authors (first_name, last_name) values ('Cassondra', 'Shelbourne');
insert into authors (first_name, last_name) values ('Elmer', 'Bisgrove');
insert into authors (first_name, last_name) values ('Annadiana', 'Monnoyer');
insert into authors (first_name, last_name) values ('Merci', 'Garrity');
insert into authors (first_name, last_name) values ('Emily', 'Penson');
insert into authors (first_name, last_name) values ('Newton', 'Le Jean');
insert into authors (first_name, last_name) values ('Zacharie', 'Linturn');
insert into authors (first_name, last_name) values ('Astra', 'Wyrill');
insert into authors (first_name, last_name) values ('Kriste', 'Jerratsch');
insert into authors (first_name, last_name) values ('Adela', 'Corkitt');
insert into authors (first_name, last_name) values ('Niall', 'Salliss');
insert into authors (first_name, last_name) values ('Dode', 'Tomasini');
insert into authors (first_name, last_name) values ('Frans', 'Mattiacci');
insert into authors (first_name, last_name) values ('Lauralee', 'Shearer');
insert into authors (first_name, last_name) values ('Fowler', 'Walbrook');
insert into authors (first_name, last_name) values ('Charisse', 'Conry');
insert into authors (first_name, last_name) values ('Donetta', 'Ianilli');
insert into authors (first_name, last_name) values ('Janna', 'Dust');
insert into authors (first_name, last_name) values ('Pattie', 'Le Brum');
insert into authors (first_name, last_name) values ('Stefan', 'Paxeford');
insert into authors (first_name, last_name) values ('Livy', 'Hairesnape');
insert into authors (first_name, last_name) values ('Samara', 'Billany');
insert into authors (first_name, last_name) values ('Janey', 'Binion');
insert into authors (first_name, last_name) values ('Eirena', 'Connolly');
insert into authors (first_name, last_name) values ('Pace', 'Cant');
insert into authors (first_name, last_name) values ('Callean', 'Gavriel');
insert into authors (first_name, last_name) values ('Christos', 'Karby');
insert into authors (first_name, last_name) values ('Gareth', 'Gerler');
insert into authors (first_name, last_name) values ('Loralie', 'Whimp');
insert into authors (first_name, last_name) values ('Jeri', 'Lowres');
insert into authors (first_name, last_name) values ('Jaimie', 'Wibrew');
insert into authors (first_name, last_name) values ('Elonore', 'Toplis');
insert into authors (first_name, last_name) values ('Tabitha', 'Wrettum');
insert into authors (first_name, last_name) values ('Riordan', 'Anetts');
insert into authors (first_name, last_name) values ('Terri', 'Grastye');
insert into authors (first_name, last_name) values ('Isa', 'Scawton');
insert into authors (first_name, last_name) values ('Carole', 'Phython');
insert into authors (first_name, last_name) values ('Melamie', 'Ffrench');
insert into authors (first_name, last_name) values ('Estevan', 'Pauly');
insert into authors (first_name, last_name) values ('Adelina', 'Ottam');
insert into authors (first_name, last_name) values ('Joseph', 'Easter');
insert into authors (first_name, last_name) values ('Jude', 'Moncrefe');
insert into authors (first_name, last_name) values ('Tynan', 'Amott');
insert into authors (first_name, last_name) values ('Barbette', 'Hadye');
insert into authors (first_name, last_name) values ('Ediva', 'Metson');
insert into authors (first_name, last_name) values ('Keenan', 'Baudic');
insert into authors (first_name, last_name) values ('Binnie', 'Archer');
insert into authors (first_name, last_name) values ('Tabbatha', 'Pickthorne');
insert into authors (first_name, last_name) values ('Dyana', 'Challes');
insert into authors (first_name, last_name) values ('Ced', 'Mc Dermid');
insert into authors (first_name, last_name) values ('Hayley', 'Hocking');
insert into authors (first_name, last_name) values ('Perla', 'Girault');
insert into authors (first_name, last_name) values ('Cale', 'Cursey');
insert into authors (first_name, last_name) values ('Chantalle', 'Rudwell');
insert into authors (first_name, last_name) values ('Claybourne', 'Dukelow');
insert into authors (first_name, last_name) values ('Rufus', 'Rathbone');
insert into authors (first_name, last_name) values ('Ryley', 'Alger');
insert into authors (first_name, last_name) values ('Erhart', 'Littell');
insert into authors (first_name, last_name) values ('Rozalie', 'Strange');
insert into authors (first_name, last_name) values ('Evanne', 'Mundle');
insert into authors (first_name, last_name) values ('Carin', 'Filon');
insert into authors (first_name, last_name) values ('Jerald', 'Dowzell');
insert into authors (first_name, last_name) values ('Alvin', 'Knowlden');
insert into authors (first_name, last_name) values ('Celisse', 'Richarz');
insert into authors (first_name, last_name) values ('Melisande', 'Ales0');
insert into authors (first_name, last_name) values ('Tiff', 'Cornthwaite');
insert into authors (first_name, last_name) values ('Nessie', 'Quemby');
insert into authors (first_name, last_name) values ('Hebert', 'Do Rosario');
insert into authors (first_name, last_name) values ('Johann', 'Krebs');
insert into authors (first_name, last_name) values ('Lonee', 'Krauze');
insert into authors (first_name, last_name) values ('Rancell', 'Toulamain');
insert into authors (first_name, last_name) values ('Kristen', 'Beharrell');
insert into authors (first_name, last_name) values ('Karyn', 'Copelli');
insert into authors (first_name, last_name) values ('Lyell', 'Adamides');
insert into authors (first_name, last_name) values ('Fabiano', 'Woodall');
insert into authors (first_name, last_name) values ('Liz', 'Marrow');
insert into authors (first_name, last_name) values ('Lacey', 'Blackmoor');
insert into authors (first_name, last_name) values ('Rossie', 'Kinney');
insert into authors (first_name, last_name) values ('Hieronymus', 'Brindle');
insert into authors (first_name, last_name) values ('Gipsy', 'Clancey');
insert into authors (first_name, last_name) values ('Drew', 'Eadie');
insert into authors (first_name, last_name) values ('Farly', 'Serridge');
insert into authors (first_name, last_name) values ('Roman', 'Mabbutt');
insert into authors (first_name, last_name) values ('Morgan', 'Noye');
insert into authors (first_name, last_name) values ('Tito', 'Calf');
insert into authors (first_name, last_name) values ('Petronia', 'Whetton');
insert into authors (first_name, last_name) values ('Abbie', 'Liston');
insert into authors (first_name, last_name) values ('Salaidh', 'Jennrich');
insert into authors (first_name, last_name) values ('Bendite', 'Yalden');
insert into authors (first_name, last_name) values ('Dennis', 'Kayes');
insert into authors (first_name, last_name) values ('Darby', 'Dakers');
insert into authors (first_name, last_name) values ('Carline', 'Sharram');
insert into authors (first_name, last_name) values ('Heidie', 'Stienham');
insert into authors (first_name, last_name) values ('Virgil', 'Wornham');
insert into authors (first_name, last_name) values ('Jodi', 'Youel');
insert into authors (first_name, last_name) values ('Erek', 'Bloschke');
insert into authors (first_name, last_name) values ('Lindi', 'Thieme');
insert into authors (first_name, last_name) values ('Meredith', 'Skalls');
insert into authors (first_name, last_name) values ('Maurise', 'Carlone');
insert into authors (first_name, last_name) values ('Sibyl', 'Bleackley');
insert into authors (first_name, last_name) values ('Ado', 'Awty');
insert into authors (first_name, last_name) values ('Almeria', 'Spare');
insert into authors (first_name, last_name) values ('Lonee', 'Stubbe');
insert into authors (first_name, last_name) values ('Grove', 'Morton');
insert into authors (first_name, last_name) values ('Devinne', 'Scotsbrook');
insert into authors (first_name, last_name) values ('Sayres', 'Burrel');
insert into authors (first_name, last_name) values ('Arielle', 'Duchateau');
insert into authors (first_name, last_name) values ('Shirley', 'Korlat');
insert into authors (first_name, last_name) values ('Lowrance', 'Sandercroft');
insert into authors (first_name, last_name) values ('Colline', 'Fossey');
insert into authors (first_name, last_name) values ('Aurora', 'Rasp');
insert into authors (first_name, last_name) values ('Elmira', 'Lenz');
insert into authors (first_name, last_name) values ('Marv', 'Toland');
insert into authors (first_name, last_name) values ('Wynn', 'Burnep');
insert into authors (first_name, last_name) values ('Zebedee', 'Trinbey');
insert into authors (first_name, last_name) values ('Olin', 'Stilliard');
insert into authors (first_name, last_name) values ('Aigneis', 'Amps');
insert into authors (first_name, last_name) values ('Janeta', 'Rankling');
insert into authors (first_name, last_name) values ('Arv', 'Wolffers');
insert into authors (first_name, last_name) values ('Joelly', 'Woodrup');
insert into authors (first_name, last_name) values ('Sarita', 'Kubanek');
insert into books (title, price, price_old, is_bestseller, author_id) values ('Trippledex', '815.28 руб.', '1356.87 руб.', false, 187);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sub-Ex', '505.8 руб.', '1273.96 руб.', false, 174);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tres-Zap', '950.81 руб.', '1459.14 руб.', true, 40);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Asoka', '437.48 руб.', '2184.52 руб.', true, 163);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sonsing', '971.21 руб.', '989.34 руб.', true, 58);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Greenlam', '1202.34 руб.', '1119.05 руб.', true, 31);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Lotlux', '833.97 руб.', '2218.06 руб.', false, 177);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tresom', '1050.78 руб.', '1510.89 руб.', false, 41);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Span', '1073.82 руб.', '1268.53 руб.', true, 160);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sonair', '998.25 руб.', '2439.47 руб.', true, 157);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tin', '625.94 руб.', '1673.36 руб.', false, 15);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tres-Zap', '463.52 руб.', '989.91 руб.', true, 107);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Regrant', '1100.13 руб.', '565.56 руб.', false, 189);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Biodex', '1200.74 руб.', '1689.84 руб.', false, 170);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Duobam', '652.14 руб.', '1660.35 руб.', false, 35);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Aerified', '1378.88 руб.', '2214.31 руб.', true, 116);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Lotstring', '518.58 руб.', '1580.07 руб.', true, 189);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Temp', '897.0 руб.', '2068.15 руб.', true, 92);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Overhold', '920.84 руб.', '2472.13 руб.', false, 172);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Prodder', '1288.34 руб.', '1818.89 руб.', true, 72);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Solarbreeze', '949.53 руб.', '1575.03 руб.', false, 159);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tin', '1173.77 руб.', '1125.35 руб.', true, 151);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Duobam', '1090.31 руб.', '669.84 руб.', false, 41);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Cardguard', '476.43 руб.', '2320.91 руб.', true, 192);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bigtax', '1270.79 руб.', '1670.26 руб.', false, 150);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Cardify', '509.07 руб.', '919.64 руб.', false, 112);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Solarbreeze', '631.69 руб.', '2169.11 руб.', true, 126);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Fixflex', '832.93 руб.', '592.27 руб.', true, 163);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Rank', '530.98 руб.', '1389.4 руб.', false, 57);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Subin', '295.35 руб.', '1786.89 руб.', true, 187);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Mat Lam Tam', '629.08 руб.', '558.72 руб.', true, 41);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Solarbreeze', '1499.6 руб.', '672.07 руб.', false, 172);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Y-find', '343.41 руб.', '2460.94 руб.', false, 117);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Viva', '828.63 руб.', '1732.48 руб.', false, 69);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Solarbreeze', '584.94 руб.', '1071.14 руб.', false, 196);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Overhold', '712.56 руб.', '2304.22 руб.', true, 129);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zathin', '577.16 руб.', '1002.43 руб.', true, 197);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zoolab', '654.78 руб.', '1564.39 руб.', true, 148);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Matsoft', '1215.53 руб.', '736.75 руб.', false, 186);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Overhold', '1245.56 руб.', '1617.22 руб.', true, 157);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Asoka', '833.67 руб.', '1925.7 руб.', true, 39);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Voyatouch', '1073.35 руб.', '1876.65 руб.', true, 147);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Alphazap', '619.67 руб.', '1797.62 руб.', false, 65);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Holdlamis', '304.7 руб.', '754.14 руб.', false, 97);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stringtough', '851.92 руб.', '2355.53 руб.', false, 57);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zaam-Dox', '907.24 руб.', '2375.46 руб.', false, 97);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Flowdesk', '1252.82 руб.', '1092.3 руб.', true, 195);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Job', '595.59 руб.', '955.89 руб.', true, 97);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Konklux', '367.03 руб.', '1566.56 руб.', false, 96);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Y-Solowarm', '1353.71 руб.', '1695.94 руб.', false, 39);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Treeflex', '497.95 руб.', '1050.02 руб.', true, 158);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Ronstring', '996.18 руб.', '1508.13 руб.', true, 155);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zamit', '634.68 руб.', '2489.46 руб.', false, 114);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Alphazap', '530.98 руб.', '535.44 руб.', true, 147);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Aerified', '1277.53 руб.', '1133.4 руб.', true, 169);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tresom', '599.85 руб.', '879.16 руб.', true, 51);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Otcom', '1391.1 руб.', '1402.6 руб.', true, 87);
insert into books (title, price, price_old, is_bestseller, author_id) values ('It', '349.37 руб.', '1359.75 руб.', false, 75);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Y-Solowarm', '610.1 руб.', '524.52 руб.', true, 61);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Temp', '816.87 руб.', '1615.25 руб.', false, 63);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Toughjoyfax', '1123.61 руб.', '1946.34 руб.', true, 17);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Konklux', '1203.1 руб.', '998.37 руб.', false, 4);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Regrant', '1120.53 руб.', '818.42 руб.', true, 29);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bigtax', '921.59 руб.', '1304.0 руб.', false, 98);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Otcom', '918.95 руб.', '2319.35 руб.', false, 122);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zathin', '1444.78 руб.', '1413.04 руб.', true, 187);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Veribet', '686.04 руб.', '875.5 руб.', true, 99);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Prodder', '417.32 руб.', '1450.06 руб.', true, 99);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stronghold', '709.59 руб.', '1184.97 руб.', false, 135);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Konklab', '1211.48 руб.', '825.98 руб.', true, 64);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Transcof', '886.98 руб.', '1620.87 руб.', true, 55);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sonsing', '858.17 руб.', '650.2 руб.', true, 27);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Toughjoyfax', '1124.73 руб.', '1793.68 руб.', true, 52);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Pannier', '995.16 руб.', '1830.99 руб.', true, 74);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Biodex', '1392.99 руб.', '800.4 руб.', false, 133);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Hatity', '1208.59 руб.', '731.02 руб.', true, 174);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stringtough', '1161.59 руб.', '1568.76 руб.', true, 110);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Domainer', '654.89 руб.', '1581.4 руб.', false, 199);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Mat Lam Tam', '376.69 руб.', '1734.64 руб.', true, 25);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Subin', '1055.84 руб.', '678.6 руб.', false, 156);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tres-Zap', '1016.15 руб.', '2343.31 руб.', false, 152);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Prodder', '611.37 руб.', '2319.1 руб.', true, 137);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zoolab', '1349.54 руб.', '2319.33 руб.', true, 15);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Duobam', '596.23 руб.', '2461.28 руб.', true, 5);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Hatity', '827.03 руб.', '1403.05 руб.', true, 71);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Fixflex', '472.13 руб.', '2202.16 руб.', false, 134);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Gembucket', '737.97 руб.', '1145.3 руб.', false, 142);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tampflex', '927.57 руб.', '719.87 руб.', false, 54);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Matsoft', '1314.23 руб.', '2224.45 руб.', true, 197);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Wrapsafe', '615.45 руб.', '2448.04 руб.', true, 136);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Y-find', '416.63 руб.', '1497.75 руб.', false, 102);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Wrapsafe', '504.94 руб.', '832.15 руб.', true, 118);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sonsing', '1078.74 руб.', '1804.28 руб.', true, 70);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Rank', '1452.83 руб.', '2300.98 руб.', false, 7);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Job', '692.86 руб.', '2355.9 руб.', false, 82);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Konklab', '1419.24 руб.', '1117.82 руб.', false, 73);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Matsoft', '877.49 руб.', '731.87 руб.', true, 122);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Voyatouch', '503.93 руб.', '1616.34 руб.', true, 10);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Andalax', '1448.23 руб.', '2463.54 руб.', false, 51);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Veribet', '1342.55 руб.', '1819.49 руб.', true, 60);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Wrapsafe', '476.8 руб.', '1418.99 руб.', true, 97);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zaam-Dox', '466.77 руб.', '2256.87 руб.', false, 27);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Opela', '717.98 руб.', '1078.98 руб.', false, 41);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tres-Zap', '551.03 руб.', '1327.95 руб.', false, 74);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Redhold', '337.03 руб.', '526.15 руб.', false, 124);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Treeflex', '631.32 руб.', '2250.19 руб.', false, 63);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Transcof', '460.78 руб.', '1940.38 руб.', false, 93);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Rank', '1075.2 руб.', '1873.6 руб.', true, 51);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Regrant', '557.67 руб.', '1775.64 руб.', true, 147);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Latlux', '711.02 руб.', '1692.99 руб.', false, 199);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tempsoft', '1124.78 руб.', '723.17 руб.', true, 18);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bamity', '1164.95 руб.', '2014.44 руб.', false, 188);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Alpha', '533.66 руб.', '841.28 руб.', false, 96);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tresom', '385.78 руб.', '776.81 руб.', true, 49);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zontrax', '1052.09 руб.', '2416.67 руб.', true, 105);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Domainer', '342.46 руб.', '1988.72 руб.', false, 4);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Overhold', '791.13 руб.', '1927.73 руб.', true, 106);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Lotlux', '1029.73 руб.', '1012.15 руб.', true, 76);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Fixflex', '1368.3 руб.', '651.51 руб.', true, 27);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tampflex', '1290.74 руб.', '1056.16 руб.', false, 62);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Transcof', '447.67 руб.', '2189.5 руб.', true, 139);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Regrant', '1100.43 руб.', '1409.66 руб.', true, 108);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Fixflex', '1458.81 руб.', '1596.3 руб.', true, 2);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Asoka', '1234.17 руб.', '1817.56 руб.', false, 9);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Viva', '1167.12 руб.', '841.78 руб.', true, 81);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Asoka', '1496.42 руб.', '1617.62 руб.', true, 61);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tres-Zap', '1088.15 руб.', '1302.59 руб.', false, 186);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stronghold', '842.89 руб.', '1811.0 руб.', true, 2);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sonsing', '652.71 руб.', '1233.29 руб.', false, 71);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Voltsillam', '1147.43 руб.', '2026.66 руб.', true, 148);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Fintone', '465.98 руб.', '1508.0 руб.', false, 138);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Solarbreeze', '525.49 руб.', '879.98 руб.', false, 164);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Flexidy', '433.06 руб.', '1118.43 руб.', false, 64);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stronghold', '1125.42 руб.', '1721.46 руб.', true, 30);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Ronstring', '1225.04 руб.', '1804.33 руб.', false, 6);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Ventosanzap', '1047.47 руб.', '984.35 руб.', false, 181);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Hatity', '671.42 руб.', '719.51 руб.', true, 134);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Duobam', '1373.9 руб.', '1928.71 руб.', false, 1);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Keylex', '1245.85 руб.', '1677.32 руб.', true, 50);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Andalax', '1476.8 руб.', '1361.12 руб.', false, 99);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Transcof', '1347.06 руб.', '1638.17 руб.', false, 148);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bigtax', '434.66 руб.', '2309.47 руб.', false, 198);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Y-Solowarm', '596.31 руб.', '520.0 руб.', false, 98);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bitchip', '932.07 руб.', '643.96 руб.', false, 168);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Hatity', '439.08 руб.', '965.71 руб.', true, 130);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tin', '865.19 руб.', '1798.8 руб.', true, 136);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Toughjoyfax', '1488.67 руб.', '1656.86 руб.', false, 174);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Subin', '624.61 руб.', '1680.97 руб.', true, 129);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zontrax', '617.51 руб.', '1106.17 руб.', false, 62);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Solarbreeze', '803.61 руб.', '501.55 руб.', true, 195);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Subin', '503.34 руб.', '1149.01 руб.', true, 37);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Alpha', '911.83 руб.', '968.66 руб.', false, 189);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tampflex', '681.85 руб.', '2222.96 руб.', false, 1);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sub-Ex', '676.97 руб.', '2249.77 руб.', true, 161);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Aerified', '1486.01 руб.', '850.14 руб.', false, 62);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Subin', '1486.17 руб.', '2417.9 руб.', false, 106);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Flowdesk', '1324.44 руб.', '2433.89 руб.', false, 175);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Gembucket', '698.62 руб.', '1447.0 руб.', false, 34);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Trippledex', '695.82 руб.', '1647.04 руб.', true, 166);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Regrant', '708.7 руб.', '989.76 руб.', false, 100);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Flowdesk', '491.43 руб.', '2348.4 руб.', true, 135);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bamity', '285.09 руб.', '676.21 руб.', true, 52);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bytecard', '406.46 руб.', '1250.01 руб.', false, 147);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Home Ing', '1336.53 руб.', '2358.81 руб.', true, 191);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Andalax', '1489.95 руб.', '1872.63 руб.', true, 132);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Otcom', '1198.89 руб.', '1806.29 руб.', false, 141);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Toughjoyfax', '459.6 руб.', '1812.15 руб.', true, 42);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Pannier', '1313.48 руб.', '1552.66 руб.', true, 123);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stim', '483.4 руб.', '1593.81 руб.', false, 172);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Konklab', '599.35 руб.', '1073.82 руб.', false, 164);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Lotstring', '546.15 руб.', '779.01 руб.', false, 128);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stim', '743.36 руб.', '1963.65 руб.', true, 180);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tampflex', '1192.73 руб.', '2271.28 руб.', true, 130);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Cardguard', '1222.73 руб.', '1158.4 руб.', true, 127);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Ronstring', '375.08 руб.', '1900.51 руб.', false, 42);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sub-Ex', '652.96 руб.', '1870.35 руб.', false, 182);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Otcom', '984.61 руб.', '2249.05 руб.', true, 177);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Greenlam', '976.98 руб.', '1443.14 руб.', false, 154);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Flowdesk', '1120.06 руб.', '922.75 руб.', true, 68);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Pannier', '1100.91 руб.', '2399.46 руб.', false, 142);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Trippledex', '386.89 руб.', '707.78 руб.', true, 182);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Job', '309.5 руб.', '2408.94 руб.', false, 50);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sonair', '656.22 руб.', '1447.26 руб.', true, 100);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zaam-Dox', '1355.05 руб.', '1622.62 руб.', false, 110);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sonsing', '1097.33 руб.', '1819.25 руб.', false, 187);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Y-find', '934.94 руб.', '783.47 руб.', false, 166);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Transcof', '600.17 руб.', '2326.48 руб.', true, 190);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Y-find', '481.39 руб.', '618.31 руб.', false, 78);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Job', '1025.66 руб.', '611.51 руб.', true, 19);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Hatity', '363.19 руб.', '1492.66 руб.', true, 152);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Biodex', '403.9 руб.', '1675.68 руб.', false, 27);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Duobam', '510.76 руб.', '2073.61 руб.', false, 160);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Regrant', '1101.29 руб.', '721.47 руб.', true, 23);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Subin', '424.45 руб.', '1431.62 руб.', false, 154);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Daltfresh', '1246.47 руб.', '2386.03 руб.', true, 23);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Ventosanzap', '711.97 руб.', '1512.22 руб.', false, 84);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Solarbreeze', '1444.51 руб.', '1596.6 руб.', false, 99);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Biodex', '1225.66 руб.', '1008.13 руб.', true, 99);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zoolab', '1121.35 руб.', '1295.1 руб.', false, 38);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Span', '350.38 руб.', '1929.43 руб.', true, 9);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zathin', '1020.11 руб.', '1625.45 руб.', true, 193);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Veribet', '798.73 руб.', '620.37 руб.', true, 128);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Voltsillam', '682.99 руб.', '517.61 руб.', true, 92);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Lotstring', '614.81 руб.', '1573.55 руб.', true, 63);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Subin', '1168.4 руб.', '1897.34 руб.', false, 78);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bitwolf', '1272.26 руб.', '1465.16 руб.', true, 59);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Lotlux', '1312.05 руб.', '2160.06 руб.', true, 44);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Home Ing', '981.38 руб.', '1878.48 руб.', true, 72);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Flexidy', '1219.8 руб.', '1206.26 руб.', true, 134);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Trippledex', '562.23 руб.', '1292.88 руб.', true, 153);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Kanlam', '1160.74 руб.', '1493.07 руб.', false, 86);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Hatity', '1087.91 руб.', '999.01 руб.', false, 157);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Voyatouch', '421.43 руб.', '2422.0 руб.', true, 169);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Quo Lux', '792.9 руб.', '1840.04 руб.', true, 197);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Treeflex', '894.96 руб.', '1968.36 руб.', true, 164);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Y-Solowarm', '1407.5 руб.', '2333.76 руб.', false, 25);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Transcof', '448.01 руб.', '810.62 руб.', true, 133);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Kanlam', '579.35 руб.', '2088.84 руб.', true, 6);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Fix San', '897.19 руб.', '1115.88 руб.', false, 80);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Job', '550.76 руб.', '1113.94 руб.', true, 10);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Gembucket', '266.35 руб.', '791.82 руб.', true, 42);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Trippledex', '325.48 руб.', '2416.46 руб.', true, 30);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Alphazap', '331.78 руб.', '1964.93 руб.', true, 103);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Duobam', '1057.21 руб.', '1633.7 руб.', true, 28);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Fix San', '576.08 руб.', '875.2 руб.', true, 82);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Lotlux', '1468.27 руб.', '1603.95 руб.', true, 35);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Quo Lux', '1300.72 руб.', '1064.15 руб.', true, 169);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Y-find', '1006.91 руб.', '1181.12 руб.', false, 11);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Namfix', '420.83 руб.', '1233.17 руб.', false, 156);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Voltsillam', '1011.37 руб.', '1383.33 руб.', false, 171);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Solarbreeze', '744.91 руб.', '2207.48 руб.', false, 9);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Flowdesk', '707.15 руб.', '1125.4 руб.', false, 130);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Overhold', '1005.64 руб.', '667.29 руб.', true, 36);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Alpha', '1117.11 руб.', '1987.25 руб.', false, 100);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sonsing', '471.26 руб.', '1134.94 руб.', false, 2);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Overhold', '1003.05 руб.', '1799.37 руб.', true, 93);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Biodex', '1293.51 руб.', '1090.8 руб.', false, 89);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bitchip', '507.45 руб.', '2467.08 руб.', false, 16);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bitchip', '1003.77 руб.', '1504.51 руб.', false, 192);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tres-Zap', '1460.35 руб.', '1727.45 руб.', false, 198);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Toughjoyfax', '964.17 руб.', '1517.82 руб.', false, 149);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Asoka', '1229.21 руб.', '2183.93 руб.', false, 120);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Namfix', '442.96 руб.', '1763.54 руб.', true, 149);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sub-Ex', '552.32 руб.', '2160.61 руб.', true, 30);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sonair', '560.85 руб.', '1253.17 руб.', false, 26);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bamity', '882.79 руб.', '1915.85 руб.', true, 186);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Ronstring', '1072.09 руб.', '2394.31 руб.', false, 63);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Cookley', '1196.07 руб.', '2461.53 руб.', true, 48);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Y-Solowarm', '536.3 руб.', '809.18 руб.', false, 124);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Holdlamis', '1474.95 руб.', '1195.17 руб.', false, 72);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Fixflex', '796.14 руб.', '1291.34 руб.', false, 75);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Redhold', '1334.2 руб.', '1438.21 руб.', false, 131);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bigtax', '439.8 руб.', '2498.11 руб.', false, 22);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Cardguard', '1280.94 руб.', '1344.85 руб.', false, 41);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Holdlamis', '1408.68 руб.', '1887.47 руб.', true, 172);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Fixflex', '290.94 руб.', '545.11 руб.', true, 188);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Cardguard', '830.01 руб.', '1862.1 руб.', false, 55);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Keylex', '1462.79 руб.', '2392.23 руб.', true, 34);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stronghold', '1295.46 руб.', '1044.59 руб.', false, 180);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stringtough', '1310.02 руб.', '1057.46 руб.', true, 150);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Solarbreeze', '784.44 руб.', '2038.09 руб.', false, 26);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tres-Zap', '642.22 руб.', '2158.74 руб.', true, 84);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Veribet', '329.1 руб.', '1554.02 руб.', true, 176);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stronghold', '1383.34 руб.', '1061.23 руб.', false, 195);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zaam-Dox', '1469.44 руб.', '767.54 руб.', true, 91);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Latlux', '1189.92 руб.', '1575.33 руб.', true, 75);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Quo Lux', '760.46 руб.', '1459.01 руб.', false, 47);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Job', '786.61 руб.', '1109.46 руб.', true, 57);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zaam-Dox', '951.36 руб.', '564.41 руб.', true, 133);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Wrapsafe', '778.47 руб.', '1172.32 руб.', true, 128);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zathin', '470.88 руб.', '1722.04 руб.', true, 66);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stronghold', '1022.29 руб.', '859.39 руб.', true, 172);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stringtough', '423.12 руб.', '1163.92 руб.', true, 16);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Home Ing', '1196.55 руб.', '1694.07 руб.', true, 145);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Quo Lux', '1195.17 руб.', '2297.44 руб.', false, 13);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Ventosanzap', '1395.1 руб.', '2392.96 руб.', false, 75);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Transcof', '659.67 руб.', '1851.97 руб.', false, 36);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Regrant', '505.02 руб.', '1215.36 руб.', false, 121);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Trippledex', '328.98 руб.', '1366.49 руб.', false, 110);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Regrant', '317.89 руб.', '2011.72 руб.', true, 200);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tres-Zap', '278.21 руб.', '1645.2 руб.', true, 176);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Ventosanzap', '347.11 руб.', '1103.57 руб.', false, 34);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Matsoft', '551.05 руб.', '2025.86 руб.', true, 131);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sub-Ex', '466.16 руб.', '2221.88 руб.', false, 60);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Matsoft', '301.82 руб.', '2188.26 руб.', true, 193);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Trippledex', '1494.06 руб.', '1634.37 руб.', false, 185);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Matsoft', '655.29 руб.', '1413.22 руб.', false, 130);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Temp', '1000.5 руб.', '1902.28 руб.', true, 105);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Vagram', '326.61 руб.', '1192.69 руб.', false, 158);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Matsoft', '652.54 руб.', '1378.15 руб.', false, 119);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Transcof', '466.28 руб.', '1971.04 руб.', false, 192);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bamity', '337.76 руб.', '971.68 руб.', true, 185);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Lotstring', '1347.99 руб.', '2364.79 руб.', false, 56);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Subin', '1128.34 руб.', '2473.44 руб.', true, 24);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Lotstring', '1483.14 руб.', '2117.87 руб.', false, 184);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Ventosanzap', '413.02 руб.', '1303.67 руб.', false, 190);
insert into books (title, price, price_old, is_bestseller, author_id) values ('It', '1051.75 руб.', '638.56 руб.', true, 74);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Keylex', '1456.1 руб.', '976.58 руб.', false, 11);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Quo Lux', '747.55 руб.', '700.38 руб.', true, 114);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sonair', '936.06 руб.', '999.9 руб.', true, 188);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Temp', '1291.0 руб.', '1393.88 руб.', false, 48);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Regrant', '795.32 руб.', '1552.65 руб.', false, 88);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Lotstring', '1327.37 руб.', '2374.8 руб.', true, 40);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Domainer', '1082.22 руб.', '658.76 руб.', true, 93);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Keylex', '1233.31 руб.', '1425.32 руб.', true, 41);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Cardguard', '695.8 руб.', '986.28 руб.', false, 10);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Treeflex', '1018.98 руб.', '663.51 руб.', false, 64);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Keylex', '531.89 руб.', '718.22 руб.', true, 164);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Veribet', '1465.69 руб.', '1909.23 руб.', true, 103);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Solarbreeze', '1316.0 руб.', '846.15 руб.', true, 100);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Mat Lam Tam', '288.07 руб.', '1572.0 руб.', true, 143);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Span', '411.02 руб.', '1443.62 руб.', false, 191);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Daltfresh', '1115.2 руб.', '1937.46 руб.', false, 5);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Prodder', '906.78 руб.', '820.4 руб.', true, 146);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Job', '480.85 руб.', '1009.33 руб.', true, 165);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Vagram', '695.15 руб.', '2368.27 руб.', true, 200);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stronghold', '669.77 руб.', '564.43 руб.', false, 191);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bitchip', '377.24 руб.', '1895.75 руб.', true, 16);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Pannier', '948.06 руб.', '1712.53 руб.', true, 181);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stim', '879.59 руб.', '1481.0 руб.', true, 163);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Kanlam', '414.38 руб.', '908.23 руб.', false, 94);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Namfix', '1483.93 руб.', '662.84 руб.', true, 52);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Trippledex', '556.6 руб.', '520.65 руб.', true, 19);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Y-find', '1158.78 руб.', '1375.53 руб.', false, 2);
insert into books (title, price, price_old, is_bestseller, author_id) values ('It', '938.47 руб.', '926.07 руб.', false, 62);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Span', '327.75 руб.', '2133.62 руб.', true, 25);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Otcom', '1214.68 руб.', '886.77 руб.', false, 63);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Rank', '556.54 руб.', '2405.19 руб.', true, 119);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Redhold', '1059.07 руб.', '1749.74 руб.', false, 22);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Gembucket', '1483.4 руб.', '1403.66 руб.', true, 47);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Temp', '1311.83 руб.', '2040.59 руб.', false, 128);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Greenlam', '614.08 руб.', '1663.25 руб.', true, 123);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Konklux', '1148.92 руб.', '1361.56 руб.', false, 131);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Voyatouch', '1007.65 руб.', '1524.42 руб.', false, 10);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Otcom', '1360.36 руб.', '958.0 руб.', true, 27);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bitchip', '621.46 руб.', '1158.38 руб.', false, 102);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Regrant', '1280.15 руб.', '1326.09 руб.', false, 99);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Temp', '1290.79 руб.', '2083.32 руб.', true, 52);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Asoka', '351.2 руб.', '1381.5 руб.', false, 147);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tresom', '536.03 руб.', '2177.81 руб.', false, 187);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Vagram', '566.17 руб.', '2419.98 руб.', true, 143);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Wrapsafe', '644.7 руб.', '2441.55 руб.', false, 141);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Kanlam', '1018.3 руб.', '1240.75 руб.', false, 191);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Latlux', '807.36 руб.', '1186.07 руб.', false, 84);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Viva', '605.27 руб.', '2117.34 руб.', true, 127);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Konklab', '362.61 руб.', '749.35 руб.', true, 44);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Temp', '1088.79 руб.', '1043.29 руб.', true, 2);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bytecard', '429.3 руб.', '534.88 руб.', false, 114);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Mat Lam Tam', '288.69 руб.', '1817.85 руб.', false, 104);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Alphazap', '740.99 руб.', '2424.41 руб.', true, 100);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Toughjoyfax', '481.4 руб.', '1612.39 руб.', false, 115);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Toughjoyfax', '1176.31 руб.', '659.57 руб.', true, 149);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Kanlam', '1046.07 руб.', '1342.26 руб.', true, 64);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Holdlamis', '464.09 руб.', '1263.7 руб.', true, 69);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Vagram', '563.32 руб.', '685.17 руб.', true, 67);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Cardguard', '543.33 руб.', '1423.45 руб.', true, 68);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Lotlux', '1332.4 руб.', '2465.19 руб.', true, 70);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Konklab', '442.99 руб.', '2467.19 руб.', false, 35);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bamity', '340.36 руб.', '1151.04 руб.', false, 55);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zontrax', '1318.91 руб.', '900.47 руб.', false, 151);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Daltfresh', '963.98 руб.', '1446.63 руб.', true, 154);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Cardify', '1452.37 руб.', '603.36 руб.', false, 176);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Span', '1448.25 руб.', '559.01 руб.', false, 196);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Treeflex', '512.38 руб.', '1378.89 руб.', false, 57);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Toughjoyfax', '431.03 руб.', '789.73 руб.', true, 178);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Mat Lam Tam', '1145.87 руб.', '1925.2 руб.', false, 97);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sonsing', '1280.66 руб.', '2393.66 руб.', true, 192);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Hatity', '1400.17 руб.', '520.41 руб.', false, 107);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Y-find', '1332.8 руб.', '1465.84 руб.', false, 103);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bitwolf', '362.31 руб.', '1290.67 руб.', true, 43);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Cardify', '770.46 руб.', '559.9 руб.', true, 57);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bytecard', '412.88 руб.', '2460.97 руб.', false, 84);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Keylex', '425.02 руб.', '1127.29 руб.', true, 153);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Rank', '943.06 руб.', '1652.75 руб.', false, 126);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sonsing', '1216.83 руб.', '1178.73 руб.', true, 188);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stronghold', '760.11 руб.', '2211.95 руб.', false, 100);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Subin', '889.63 руб.', '738.58 руб.', true, 127);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bigtax', '1337.24 руб.', '1933.18 руб.', true, 193);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bitchip', '1264.81 руб.', '920.79 руб.', false, 90);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bamity', '463.15 руб.', '1734.24 руб.', false, 149);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Mat Lam Tam', '417.59 руб.', '1739.67 руб.', false, 198);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Lotstring', '951.51 руб.', '1118.76 руб.', false, 196);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tampflex', '1106.45 руб.', '805.33 руб.', false, 113);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Redhold', '882.19 руб.', '1162.14 руб.', false, 133);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Cardguard', '1494.94 руб.', '1654.33 руб.', true, 46);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Treeflex', '408.42 руб.', '586.44 руб.', false, 20);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tempsoft', '1021.62 руб.', '2284.92 руб.', true, 45);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Greenlam', '779.47 руб.', '1347.88 руб.', true, 166);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sonsing', '1141.23 руб.', '1071.08 руб.', true, 148);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Mat Lam Tam', '397.95 руб.', '2428.28 руб.', false, 142);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Viva', '714.51 руб.', '2472.23 руб.', false, 23);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Fixflex', '806.68 руб.', '1489.39 руб.', true, 61);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Vagram', '347.36 руб.', '566.27 руб.', false, 15);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Wrapsafe', '1323.34 руб.', '1587.72 руб.', false, 191);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Redhold', '1091.48 руб.', '1476.48 руб.', false, 74);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Voyatouch', '583.37 руб.', '538.06 руб.', false, 101);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Overhold', '844.44 руб.', '963.41 руб.', false, 97);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sonsing', '834.88 руб.', '923.84 руб.', false, 139);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Solarbreeze', '1461.27 руб.', '1624.02 руб.', true, 174);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Asoka', '772.43 руб.', '1948.59 руб.', true, 69);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Duobam', '1362.72 руб.', '983.13 руб.', false, 53);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Lotstring', '943.2 руб.', '510.92 руб.', true, 76);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Ventosanzap', '889.7 руб.', '1074.53 руб.', false, 119);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zamit', '704.8 руб.', '2115.82 руб.', false, 131);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tres-Zap', '1193.7 руб.', '1780.23 руб.', false, 191);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sub-Ex', '933.24 руб.', '2265.79 руб.', true, 133);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bitwolf', '1477.25 руб.', '1788.43 руб.', false, 75);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zoolab', '1469.74 руб.', '1896.82 руб.', false, 183);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Ronstring', '1435.68 руб.', '1018.99 руб.', false, 9);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Job', '1311.4 руб.', '1917.31 руб.', false, 110);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Konklux', '325.37 руб.', '2163.4 руб.', false, 79);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Ronstring', '504.68 руб.', '1584.95 руб.', true, 189);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Y-find', '805.96 руб.', '1768.55 руб.', false, 32);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bigtax', '346.25 руб.', '1113.13 руб.', false, 25);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Quo Lux', '688.02 руб.', '1506.83 руб.', false, 103);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Konklab', '892.13 руб.', '823.16 руб.', true, 15);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Namfix', '812.61 руб.', '1577.01 руб.', true, 21);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Alphazap', '1479.5 руб.', '1383.88 руб.', true, 104);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Y-find', '1394.57 руб.', '2229.84 руб.', true, 142);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Namfix', '859.93 руб.', '1617.38 руб.', false, 123);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Transcof', '385.65 руб.', '2383.8 руб.', true, 170);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Lotlux', '668.38 руб.', '936.43 руб.', true, 146);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Subin', '312.71 руб.', '1866.8 руб.', true, 93);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bamity', '603.74 руб.', '510.92 руб.', false, 192);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Pannier', '875.89 руб.', '785.82 руб.', true, 109);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bamity', '1287.2 руб.', '787.78 руб.', false, 16);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Toughjoyfax', '365.94 руб.', '1343.75 руб.', true, 12);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zaam-Dox', '1054.54 руб.', '1294.59 руб.', true, 182);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stringtough', '1406.35 руб.', '828.86 руб.', false, 4);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tresom', '904.81 руб.', '2023.27 руб.', false, 188);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stronghold', '858.67 руб.', '1447.83 руб.', true, 136);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tempsoft', '554.82 руб.', '704.91 руб.', true, 178);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tres-Zap', '1315.19 руб.', '1765.15 руб.', true, 90);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Job', '809.83 руб.', '1164.69 руб.', false, 20);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Solarbreeze', '750.42 руб.', '878.98 руб.', false, 55);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bytecard', '941.6 руб.', '1623.78 руб.', true, 95);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Subin', '1466.38 руб.', '673.41 руб.', true, 124);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Alpha', '422.69 руб.', '2248.56 руб.', false, 72);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Gembucket', '1106.35 руб.', '2343.34 руб.', true, 58);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Hatity', '809.62 руб.', '1424.6 руб.', true, 139);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Greenlam', '1127.08 руб.', '2390.28 руб.', true, 103);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Trippledex', '1296.48 руб.', '1667.54 руб.', true, 171);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Duobam', '577.27 руб.', '2430.65 руб.', false, 80);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tin', '263.0 руб.', '1603.86 руб.', true, 60);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Quo Lux', '335.94 руб.', '1282.46 руб.', false, 118);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tampflex', '543.98 руб.', '503.66 руб.', false, 121);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stronghold', '628.66 руб.', '722.32 руб.', true, 146);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Y-find', '688.03 руб.', '1388.89 руб.', false, 155);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Namfix', '271.55 руб.', '2155.05 руб.', true, 18);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Alphazap', '811.14 руб.', '1056.1 руб.', true, 97);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zaam-Dox', '1496.18 руб.', '754.09 руб.', true, 4);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Duobam', '1463.63 руб.', '737.03 руб.', false, 52);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stronghold', '590.18 руб.', '1344.51 руб.', true, 27);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Flexidy', '282.23 руб.', '539.31 руб.', true, 188);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Gembucket', '1472.22 руб.', '2344.41 руб.', true, 5);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Sonair', '292.1 руб.', '1316.71 руб.', true, 200);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Trippledex', '1091.82 руб.', '748.63 руб.', false, 3);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Veribet', '950.64 руб.', '888.31 руб.', true, 22);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tempsoft', '535.65 руб.', '1075.09 руб.', true, 121);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Lotstring', '541.16 руб.', '1823.03 руб.', false, 90);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Solarbreeze', '1414.22 руб.', '877.95 руб.', true, 151);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Treeflex', '805.37 руб.', '2328.11 руб.', true, 142);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Overhold', '1082.13 руб.', '1632.98 руб.', false, 91);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Konklux', '661.79 руб.', '2241.83 руб.', true, 105);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Flowdesk', '948.87 руб.', '1340.45 руб.', false, 119);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Regrant', '1128.42 руб.', '1375.58 руб.', false, 90);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tres-Zap', '1354.72 руб.', '1628.25 руб.', false, 76);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bamity', '1245.55 руб.', '650.99 руб.', false, 33);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Voltsillam', '733.33 руб.', '1733.32 руб.', false, 54);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Gembucket', '1102.16 руб.', '1194.43 руб.', false, 140);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zamit', '1010.6 руб.', '1137.88 руб.', true, 60);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Daltfresh', '365.43 руб.', '1935.25 руб.', false, 91);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Transcof', '1075.33 руб.', '1605.06 руб.', true, 45);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Namfix', '798.46 руб.', '1039.53 руб.', false, 90);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Rank', '993.81 руб.', '2445.44 руб.', true, 192);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Toughjoyfax', '763.31 руб.', '1503.08 руб.', false, 182);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Subin', '1463.09 руб.', '1673.33 руб.', false, 72);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zontrax', '722.67 руб.', '1097.05 руб.', false, 54);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Gembucket', '311.1 руб.', '757.32 руб.', false, 34);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Ventosanzap', '546.04 руб.', '561.38 руб.', true, 92);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Span', '454.89 руб.', '1228.65 руб.', false, 135);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tin', '414.25 руб.', '527.17 руб.', false, 196);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bigtax', '1327.83 руб.', '1219.48 руб.', true, 9);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Zathin', '365.47 руб.', '1658.98 руб.', true, 146);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Domainer', '1419.05 руб.', '751.9 руб.', true, 184);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Redhold', '1018.9 руб.', '2081.76 руб.', false, 37);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Alphazap', '1328.0 руб.', '1102.55 руб.', true, 37);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Vagram', '1122.01 руб.', '1999.49 руб.', false, 194);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Voltsillam', '1369.54 руб.', '1394.18 руб.', false, 125);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Gembucket', '531.43 руб.', '1312.96 руб.', true, 96);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Fixflex', '796.33 руб.', '1670.76 руб.', false, 127);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Trippledex', '1384.15 руб.', '1907.23 руб.', false, 24);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Stim', '706.13 руб.', '1371.57 руб.', true, 45);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Flowdesk', '815.57 руб.', '568.04 руб.', true, 197);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Konklux', '869.29 руб.', '2416.25 руб.', true, 24);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Viva', '1192.19 руб.', '2146.46 руб.', true, 107);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Bitwolf', '1057.24 руб.', '1169.53 руб.', false, 114);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Tres-Zap', '1309.0 руб.', '2195.28 руб.', true, 8);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Duobam', '1139.6 руб.', '637.03 руб.', false, 102);
insert into books (title, price, price_old, is_bestseller, author_id) values ('Hatity', '903.25 руб.', '1108.66 руб.', true, 43);
