DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;
DROP SEQUENCE IF EXISTS author_id_seq;

CREATE SEQUENCE author_id_seq START 1001;
CREATE TABLE  books(
id BIGSERIAL PRIMARY KEY,
author_id INTEGER,
author VARCHAR(250) NOT NULL,
title VARCHAR(250) NOT NULL,
priceOld  VARCHAR(20) DEFAULT NULL,
price VARCHAR(20) DEFAULT NULL
);

CREATE TABLE authors(
id INTEGER DEFAULT NEXTVAL('author_id_seq') PRIMARY KEY,
author VARCHAR(250),
last_name VARCHAR (250),
first_name VARCHAR (250)
-- FOREIGN KEY (author) REFERENCES books(author)
);